## 一、张量的属性

In [7]:
import torch
import numpy as np

In [3]:
t = torch.Tensor()
type(t)

torch.Tensor

### 张量的数据类型

In [4]:
t.dtype  # 张量的数据类型

torch.float32

### 张量的设备

In [5]:
t.device

device(type='cpu')

### 张量在内存中的存储方式

In [6]:
t.layout

torch.strided

## 二、使用数据创建张量

In [8]:
data = np.array([1,2,3])  # data的数据类型是numpy.ndarray
type(data)

numpy.ndarray

In [11]:
o1 = torch.Tensor(data)
o2 = torch.tensor(data)
o3 = torch.as_tensor(data)
o4 = torch.from_numpy(data)

print(o1)  
print(o2)
print(o3)
print(o4)

# o1数字后面有圆点，表示是浮点数，其余的类型是int32
print(o1.dtype)
print(o2.dtype)
print(o3.dtype)
print(o4.dtype)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
torch.float32
torch.int32
torch.int32
torch.int32


### 用dtype参数指定生成tensor的类型

In [14]:
t1 = torch.tensor(data, dtype=torch.float32)
t2 = torch.as_tensor(data, dtype=torch.float32)

print(t1)
print(t2)
print(t1.dtype)
print(t2.dtype)

tensor([1., 2., 3.])
tensor([1., 2., 3.])
torch.float32
torch.float32


### 数据的复制与共享内存

In [15]:
print('old:', data)

old: [1 2 3]


In [16]:
# 修改原始数据中的值
data[0] = 0   

In [17]:
print('new:', data)

new: [0 2 3]


In [18]:
# 查看修改原始数据的值对生成的tensor是否有影响
# 其中o1,o2没有发生改变，说明这两种方式创建的tensor是复制了原数据
# 其中o3,o4发生改变，说明这两种方式创建的tensor与原数据共享内存

print(o1)  
print(o2)
print(o3)
print(o4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([0, 2, 3], dtype=torch.int32)
tensor([0, 2, 3], dtype=torch.int32)


### 把已有的tensor类型转为numpy类型

In [19]:
print(o3.numpy())
print(o4.numpy())

[0 2 3]
[0 2 3]


In [20]:
print(type(o3.numpy()))
print(type(o4.numpy()))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## 三、reshape
### reshape()函数和view()函数功能相同

In [21]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [22]:
t.size()  # 获取tensor形状

torch.Size([3, 4])

In [24]:
t.shape   # 获取tensor形状

torch.Size([3, 4])

### 查看tensor中元素的数量

In [25]:
t.numel()

12

### 不改变阶的reshape

In [26]:
t.reshape([1,12])

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [27]:
t.reshape([2,6])

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [28]:
t.reshape([3,4])

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [29]:
t.reshape([4,3])

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [30]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

### 改变阶的reshape

In [31]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [32]:
t.reshape(2,2,-1)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])