#### 1.在一个for循环中遍历两个list

In [1]:
list1 = [1, 6, 2, 4]
list2 = ['a', 'b', 'c', 'd', 'e']  # 没有配对的元素不会输出

for item1, item2 in zip(list1, list2):
    print(item1, item2)


1 a
6 b
2 c
4 d


#### 2.输出一个list中的元素和对应的索引

In [2]:
my_list = ['苹果', '橙子', '香蕉', '西瓜']

for index, element in enumerate(my_list):
    print(f"索引 {index} 对应的元素是: {element}")


索引 0 对应的元素是: 苹果
索引 1 对应的元素是: 橙子
索引 2 对应的元素是: 香蕉
索引 3 对应的元素是: 西瓜


In [3]:
#### 1.在一个for循环中遍历两个list

list1 = [1, 2, 3, 4]
list2 = ['a', 'b', 'c', 'd', 'e']  # 没有配对的元素不会输出

for item1, item2 in zip(list1, list2):
    print(item1, item2)


#### 2.输出一个list中的元素和对应的索引

my_list = ['苹果', '橙子', '香蕉', '西瓜']

for index, element in enumerate(my_list):
    print(f"索引 {index} 对应的元素是: {element}")


1 a
2 b
3 c
4 d
索引 0 对应的元素是: 苹果
索引 1 对应的元素是: 橙子
索引 2 对应的元素是: 香蕉
索引 3 对应的元素是: 西瓜


#### 3.按大列表中列表的某个位置元素排序大列表

In [4]:
import numpy as np
random_matrix = np.random.rand(4, 3)
print(random_matrix)

[[0.16671224 0.1919749  0.88104686]
 [0.44677965 0.7258295  0.19093829]
 [0.89812016 0.47612061 0.53756458]
 [0.92582971 0.42392845 0.62208653]]


In [5]:
sorted_matrix = sorted(random_matrix, key=lambda x: x[0]) # 按小列表中的第一个元素排序整个列表
sorted_matrix

[array([0.16671224, 0.1919749 , 0.88104686]),
 array([0.44677965, 0.7258295 , 0.19093829]),
 array([0.89812016, 0.47612061, 0.53756458]),
 array([0.92582971, 0.42392845, 0.62208653])]

#### 4.在循环中往list添加元素，循环结束后再清空list

In [1]:
# 初始化一个空列表
my_list = []

# 假设我们正在进行某种循环操作
for i in range(10):
    # 往列表中添加元素
    my_list.append(i * 2)

# 循环结束，此时my_list中已经包含了循环内添加的所有元素
print("After loop: ", my_list)

# 清空列表
my_list.clear()

# 现在my_list为空
print("After clearing: ", my_list)

After loop:  [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
After clearing:  []


#### 5.统计list中每个元素出现的次数
- collections.Counter：统计元素数量，然后计数并返回一个字典，键为元素，值为元素个数。

In [2]:
from collections import Counter

def count_element_occurrences(lst):
    counter = Counter(lst)
    return counter

# 示例用法
my_list = [1, 2, 3, 2, 7, 8, 9, 1, 2, 4, 5, 5]
element_counts = count_element_occurrences(my_list)
print(element_counts)

Counter({2: 3, 1: 2, 5: 2, 3: 1, 7: 1, 8: 1, 9: 1, 4: 1})


#### 6.list中同时添加多个元素
- extend()

In [3]:
# Initial list
numbers = [1, 2, 3]

# Another iterable (list)
a=4
b=5
c=6

# Extend the initial list with the contents of the other iterable
numbers.extend([a,b,c])

# Now numbers is [1, 2, 3, 4, 5, 6]
print(numbers)

[1, 2, 3, 4, 5, 6]


In [6]:
a = []
a.append([3,4])
print(a)

[[3, 4]]
